name: build-container
on:
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure git for private module
        run: |
          git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/basili4-1982/".insteadOf "https://github.com/basili4-1982/"
          go env -w GOPRIVATE=github.com/basili4-1982/*
          go mod download

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Run tests
        run: go test ./...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Docker tags
        id: meta
        run: |
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          BASE_IMAGE="${{ env.REGISTRY }}/${REPO_LOWER}"
          
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
              BRANCH="${{ github.head_ref }}"  # ветка PR
              else
            BRANCH="${{ github.ref_name }}"  # ветка push
          fi

          # Короткий хеш коммита
          SHORT_SHA="${GITHUB_SHA::7}"

          # Массив для тегов
          TAGS=()

          # Всегда добавляем тег с хешем коммита
          TAGS+=("${BASE_IMAGE}:${BRANCH}-${SHORT_SHA}")

          # Если это master ветка, добавляем latest
          if [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            TAGS+=("${BASE_IMAGE}:latest")
          fi

          # Если это pull request, добавляем тег с номером PR
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            TAGS+=("${BASE_IMAGE}:pr-${{ github.event.pull_request.number }}")
          fi

          # Объединяем теги через запятую
          TAGS_STRING=$(IFS=,; echo "${TAGS[*]}")
          echo "tags=${TAGS_STRING}" >> $GITHUB_OUTPUT

          echo "Generated tags: ${TAGS_STRING}"



      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            TOKEN=${{ secrets.GO_ACTIONS_TOKEN }}
            USER=${{ github.repository_owner }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
    outputs:
      tags: ${{ steps.meta.outputs.tags }}